name: Release

on:
  push:
    tags:
      - '*'

jobs:
  test:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Install dependencies
        run: pip3 install -r requirements.txt
      - name: Build
        run: python3 -m build
      - name: Upload
        run: python3 -m twine upload -u ${{ secrets.PYPI_USERNAME }} -p ${{ secrets.PYPI_PASSWORD }} dist
